// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj5Q7LuAGZGCLyQoi3WD0Qwygjyo49SoE',
    appId: '1:119077890778:android:776637c77bb0808642d3e3',
    messagingSenderId: '119077890778',
    projectId: 'hangry-app-aff01',
    databaseURL: 'https://hangry-app-aff01-default-rtdb.firebaseio.com',
    storageBucket: 'hangry-app-aff01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLCgzjIxtvfVC3XEhYpqNCLvjZZzizWlE',
    appId: '1:119077890778:ios:7da7eb3147bc26ac42d3e3',
    messagingSenderId: '119077890778',
    projectId: 'hangry-app-aff01',
    databaseURL: 'https://hangry-app-aff01-default-rtdb.firebaseio.com',
    storageBucket: 'hangry-app-aff01.firebasestorage.app',
    iosBundleId: 'com.example.hangryAppFlutter',
  );
}
